<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/shine/storage/base');


phutil_require_source('ShineBadge.php');
